name: "New-ReleaseNotesFromChangeLog"
description: "Create ReleaseNotes.md from ChangeLog.md with version filter"
author: "Sergey.S.Betke@yandex.ru"
branding:
  icon: "package"
  color: blue
inputs:
  change-log-path:
    description: "relative path to ChangeLog.md file"
    required: false
    default: "CHANGELOG.md"
  release-notes-path:
    description: "relative path to ReleaseNotes.md file"
    required: false
    default: "RELEASENOTES.md"
  version:
    description: "project version, for which ReleaseNotes.md must be generated"
    required: false
    default: "latest"
  version2:
    description: "project version, for which ReleaseNotes.md must be generated"
    required: false
    default: "latest"
  verbose:
    description: "verbose output"
    required: false
    default: "true"
outputs:
  release-notes-path:
    description: "full path to generated ReleaseNotes.md file"
    value: ${{ steps.main.outputs.release-notes-path }}
  actual-version:
    description: "actual project version, for which ReleaseNotes.md generated (used if version param does not specified)"
    value: ${{ steps.main.outputs.actual-version }}
runs:
  using: "composite"
  steps:
    - id: main
      shell: pwsh
      run: |
        Write-Output ( "Version: $env:INPUT_VERSION" );
        Write-Output ( "Version2: $env:INPUT_VERSION2" );
        . "${{ github.action_path }}/Invoke-GitHubAction.ps1";
